### ISSUE TITLE
Support for VFX Graph

### ISSUE THREAD

**Issue by aman-tiwari** [keijiro/DFVolume#1]
It would be cool for this to support the VFX Graph. All it would take would be changing this line: https://github.com/keijiro/DFVolume/blob/master/Assets/DFVolume/VolumeSampler.cs#L79 so that the distance is stored in the red channel, rather than the alpha channel.

**Comment by keijiro** [comment]
I thought that VFX Graph requires **signed** distance fields so that DFVolume (only supports **unsigned** distance fields) can't be helpful for it. Does the change you suggested actually work?

**Comment by aman-tiwari** [comment]
It worked well for me with the Confrom To SDF block. I'm not sure if float textures can support signed values anyway.

**Comment by aman-tiwari** [comment]
The distance field being unsigned means that the object ends up being hollow in the end. I'm not sure what the easiest way to get it working solidly would be though

**Comment by keijiro** [comment]
Okay. Thanks for the input. I'll rethink it when I start working on VFX Graph.

**Comment by keijiro** [comment]
Now VFX Graph has its own SDF baking tool (from Unity 2021.2). I'm closing this issue because it's not needed anymore.
